# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgiaa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='palheta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
